name: Snyk
on:
  push:
    branches:
      - nb4-maintenance

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          THIS_BRANCH:  ${GITHUB_REF##*/}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk.sarif --target-reference="${THIS_BRANCH}"
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-results.sarif
